server:
  port: 8091

spring:
  application:
    name: excel-demo
  datasource:
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/excel?useUnicode=true&characterEncoding=utf8&useSSL=false
    driver-class-name: com.mysql.jdbc.Driver

mybatis:
  #mapper-locations: file:${user.dir}/config/mapping/*Mapping.xml
  mapper-locations: classpath:mapping/*Mapping.xml
  type-aliases-package: com.excelDemo.entity